spring:
  application:
    name: hhplus
  profiles:
    active: local
  datasource:
    name: HangHaePlusDataSource
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 3
      connection-timeout: 10000
      max-lifetime: 60000
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: false
    hibernate:
      # 운영 상황 시 none이지만 현재 프로젝트는 update 진행
      ddl-auto: update
    properties:
      hibernate.timezone.default_storage: NORMALIZE_UTC
      hibernate.jdbc.time_zone: UTC

security:
  jwt:
    access:
      secret: access_secret_access_secret_acce
      expiration: 900        # 15분
    refresh:
      secret: refresh_secret_refresh_secret_re
      expiration: 1209600   # 14일

---
spring.config.activate.on-profile: local, test

spring:
  datasource:
    url: jdbc:mysql://localhost:53306/hhplus?characterEncoding=UTF-8&serverTimezone=UTC
    username: application
    password: application
  data:
    redis:
      host: localhost
      port: 56379